[package]
name = "vlife-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22"
env_logger = "0.10"
num-traits = "0.2"
nalgebra = "0.32"

vlife-physics = { path = "../vlife-physics" }
vlife-simulator = { path = "../vlife-simulator" }