[package]
name = "vlife-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
#vlife-macros = { path = "../vlife-macros" }

indexmap = "2.0"
#itertools = "0.11"
nalgebra = "0.32"
num-traits = "0.2"
ordered-float = "4.0"
paste = "1.0"
rand = "0.8"
