[package]
name = "vlife-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.0"
nalgebra = "0.32"
num-traits = "0.2"
paste = "1.0"
rand = "0.8"

vlife-physics = { path = "../vlife-physics" }